export { EditIcon } from './EditIcon'
export { TrashIcon } from './TrashIcon'
export { PlusIcon } from './PlusIcon'
export { HomeIcon } from './HomeIcon'
export { SettingIcon } from './SettingIcon'
export { SlidersIcon } from './SlidersIcon'
export { LogoutIcon } from './LogoutIcon'
export { ArrowUpIcon } from './ArrowUpIcon'
export { UploadIcon } from './UploadIcon'

export type { IconElement } from './types'
